version: "2"
services:
    nginx:
        image: nginx:latest
        container_name: nginx2
        ports:
            - "80:80"
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
            SERVER_NAME: ${NGINX_SERVER_NAME}
        volumes:
            - ./nginx:/etc/nginx/conf.d/
            - ./lol2youtube/staticfiles:/staticfiles
        depends_on:
            - web

    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web2
        command: bash -c "cd lol2youtube && ./entrypoint.sh"
        volumes:
            - ./lol2youtube:/lol2youtube
        depends_on:
            db:
                condition: service_healthy

    db:
        image: postgres:latest
        container_name: postgres2
        ports:
            - "5433:5432"
        shm_size: 1gb
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./pg/data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5
